### ISSUE TITLE
Shift-Click

### ISSUE THREAD

**Issue by DarkLegendPT** [Rikmuld/CampingMod-mcmod#126]
Hello,

Can u please launch a version for MC 1.7.10 where shift-click works in backpack? Also if u have "keepInventory" set to true, u dont lose ur stuff on the GUI.

Just that. Please. I still play 1.7.10 because i dont like 1.8+ new mechanics, and I love 1.7.10 mods also, is there a lot more mods for 1.7.10

Ty.

**Comment by rikmuld** [comment]
Sorry, I don't have the time to maintain this mod for more than one version of Minecraft.
