### ISSUE TITLE
Hemp not consumed after planting

### ISSUE THREAD

**Issue by Error998** [Rikmuld/CampingMod-mcmod#14]
The Camping Mod Version: 2.1c
Forge Version: 10.13.2.1236
Minecraft Version: 1.7.10
Tested on Multiplayer

Steps to reproduce issue:
* Plant hemp on some sand next to a water source

Result:
* Plant is planted but the hemp is still in the inventory
* Not sure if this is a bug or a feature as I was expecting it to work like a normal seed?
* Current mechanic gives you invite hemp plants 0_o

**Comment by Rikmuld** [comment]
Thank you for reporting the issue, I shall look into it as soon as possible.

**Comment by Rikmuld** [comment]
fixed
