### ISSUE TITLE
Curseforge Missing Corefiles for 1.7.x -1.9X Alternate DL Links Broken due to offline website

### ISSUE THREAD

**Issue by mikeloeven** [Rikmuld/CampingMod-mcmod#157]
Unsure if this should go in MC Camping or MC Core but the Core jar files for versions 1.7.X-1.9.X are missing from the curse forge website. Currently the alternate download links are non functional as rikmuld.com is currently down. It is currently impossible to install MC-Camping if you are running something like FTB as a base due to the missing files. It took a while to locate a working version of the file but such searches typically lead to sketchy mirror sites with increased risk of virus or malware. For the sake of your users please make sure to re upload the missing legacy core versions to curse forge or at least provide a working official download mirror for these versions. even on github the only branch i found was 1.8 and it does not appear to have a compiled release available 

thanks

**Comment by rikmuld** [comment]
Thanks for the heads up, the website is back online (you can find it on http://mc.rik.me), versions go back to 1.4.7. I'll put it all on curse forge as well if I find some time.

**Comment by mikeloeven** [comment]
Ah i see the domain changed looks like alot of wikis and listings still point to the original domain

**Comment by mikeloeven** [comment]
@rikmuld one more minor thing. on the curse forge description page the new URL has a extra / at the end with is breaking the redirect
