### ISSUE TITLE
Crash when placing map into camping inventory

### ISSUE THREAD

**Issue by BlooBeuts** [Rikmuld/CampingMod-mcmod#19]
http://pastebin.com/m2MS1wpu

My daughter had VoxelMap installed, and my son didn't. She was aggravated over being the only one with a minimap, so she gave him a map to place into one of the slots in his camping inventory in the hopes that it would give him some similar functionality. It crashed him out; now when he tries to join the server, it loads his HUD and some scenery, but as soon as a map starts to appear in the top right corner, he crashes to desktop.

I'm going to work around it for now by uninstalling/reinstalling CampingMod2 for the server and not using maps with it :)

**Comment by BlooBeuts** [comment]
Opened my son's .dat file with NBTExplorer 2.7.5, and it showed him with zero inventory. Problem solved by deleting his saved data, without messing with the mod files.

**Comment by Rikmuld** [comment]
Fixed, mod will be updated soon.
