### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by StarfireSky** [Rikmuld/CampingMod-mcmod#20]
When I try to put the tent down it crashes the game.

**Comment by Rikmuld** [comment]
What version are you using?

**Comment by StarfireSky** [comment]
I am using version 1.7.10 and forge is at 10.13.2.1307 does this help. 


On Saturday, February 28, 2015 7:55 AM, Rik Mulder <notifications@github.com> wrote:
  


What version are you using?

**Comment by Rikmuld** [comment]
Version as in version of the mod. The error you are reporting (if I guess right since you haven't included a crash report) is one fixed in the newest version 2.1e. So if you are using a lower version, updating the mod should fix.
