### ISSUE TITLE
Kits Bug

### ISSUE THREAD

**Issue by Fenice530** [Rikmuld/CampingMod-mcmod#23]
When I use the campfire base and I'll put the grill kit or the pan kit does not work and the last download (as for version 1.7.10) does not have all that you showed you during the video type rabbits and deer or the camping guide

**Comment by Rikmuld** [comment]
Fixed, an update will be available soon.

**Comment by Fenice530** [comment]
exactly when the update will be released

**Comment by Rikmuld** [comment]
Most likely tomorrow.
