### ISSUE TITLE
Shift right click don't work in inventory

### ISSUE THREAD

**Issue by Jeebeevee** [Rikmuld/CampingMod-mcmod#29]
If the option 'Core Features Only' is false in de config file the shift right click with any item won't work.
Is the option is true, shift right click works. Only thing then is that there is no world gen. 

I think this is a bug, and love to see it fixed.

======== option in config =========
general {
    # Only use the core features of the camping mod. WARNING! use carfully! [default: false]
    B:"Core Features Only"=false

**Comment by BlooBeuts** [comment]
I have not been able to shift-click items from my hotbar into my inventory since updating to v2.1g. Shift-clicking from one inventory to another works as normal (e.g., from my inventory to a chest or vice-versa). I am using Inventory Tweaks 1.58, in case that matters.

**Comment by Rikmuld** [comment]
Fixed
