### ISSUE TITLE
Problem slot with inventory (in camping mod)

### ISSUE THREAD

**Issue by Sprik07** [Rikmuld/CampingMod-mcmod#30]
When one dies the bag drop (and other items campingmod in tab), but it is always on us(Duplicate).
 Is this normal or a bug?

Example :
![normal](https://cloud.githubusercontent.com/assets/8299700/7274953/563c074a-e901-11e4-8602-f45921d3b8f3.PNG)

I am died :
![bag drop on the ground and in my inventory](https://cloud.githubusercontent.com/assets/8299700/7274994/9363886e-e901-11e4-9b53-cea456f9a28a.PNG)

Duplicate proof :
![bug](https://cloud.githubusercontent.com/assets/8299700/7275010/ac37f79e-e901-11e4-8b25-760ec1b1c951.PNG)

I await your response. :)
Bye.

**Comment by Rikmuld** [comment]
I tried a lot, but I'm unable to get my bag to duplicate. 

What server are you using? Does it also happen with you in singleplayer?
