### ISSUE TITLE
Feature Request: Configurable Food for the Campfire Kits

### ISSUE THREAD

**Issue by PitchBright** [Rikmuld/CampingMod-mcmod#31]
There are a lot of mods out there that add different types of Food. It's really unfortunate to not be able to use any of them. It would be amazing to have a section in the config file where we could config what food types (input, output) we would like our users to be able to cook in each of the Kits.

**Comment by Rikmuld** [comment]
I'll be sure to include this feature in the 1.8 update.

**Comment by PitchBright** [comment]
No love for the 1.7.10?

**Comment by Rikmuld** [comment]
Sorry, I will only work on 1.8.

I also remember that cookable food added by other mods are actually already cookable in Campfires. Most of it will be cookable on a cooking campfire with a pan-kit installed and some will be cookable with the grill-kit. If the food is meat it will more likely be cookable with the grill (I never tested it myself though, but it should work.....).

At last expect this feature included in one of the upcoming updates (probably not the next).
