### ISSUE TITLE
when i try to add your mod seems something doesn't work

### ISSUE THREAD

**Issue by lightning02** [Rikmuld/CampingMod-mcmod#32]
seems that something is missing but i have no idea what "corerm" is.
http://i.imgur.com/q3Qvtof.png

**Comment by lightning02** [comment]
http://pastebin.com/MyQjQSg1

**Comment by Rikmuld** [comment]
If you read the install instructions on http://rikmuld.com/camping/download you'll see that you need the download: "RikMuld's Core" (=="corerm") in order for "The Camping Mod" to work. The download for the core can be found on the same page as the download for the Camping Mod.

This has recently changed. I'm sorry if the download page wasn't clear enough and for the inconvenience of needing to download two different things. I hope you don't mind.

**Comment by lightning02** [comment]
Oh.. really thanks!! you have been very kind!!
