### ISSUE TITLE
Crash when rendering food cooking on a campfire

### ISSUE THREAD

**Issue by BlooBeuts** [Rikmuld/CampingMod-mcmod#34]
My daughter got this crash earlier today, and I was able to reproduce it.

Her log: http://pastebin.com/qhk6bMFz
My log: http://pastebin.com/YKEd1k8x

**Comment by Rikmuld** [comment]
Added some safeties during rendering, it should be fixed with that. An update will be available soon (it will be for Minecraft 1.8).
