### ISSUE TITLE
Inventory overwrites NEI recipe when called from WAILA with numpad 3 or 4

### ISSUE THREAD

**Issue by BlooBeuts** [Rikmuld/CampingMod-mcmod#35]
When looking at a block with WAILA, the default behavior is that pressing 3 on the number pad at the right of the keyboard will bring up the recipe for that block in NEI as though the user had highlighted a block in the NEI menu and pressed R; default behavior in the same situation is that pressing 4 will call NEI for the highlighted block as though U had been pressed in the menu. Very useful! Since upgrading from v2.1e of The Camping Mod to v2.1g, pressing 3 or 4 briefly flashes the correct NEI function, and then the recipe GUI is overwritten by the player's inventory GUI. Perhaps this is related to the way that The Camping Mod adds its new inventory tabs?

Here is the list of mods I am using, in case that is of any help / interest: http://pastebin.com/DttvsnG6

**Comment by TopStiGear** [comment]
I am having a similar issue with the crafting menu/ GUI and other mods, is it possible to use a 3rd party mod such as baubles to change and stop the bugs from happening.

My Modpack/ Mod List: http://www.technicpack.net/modpack/tsg-infinity-plus.672994

**Comment by Rikmuld** [comment]
@BlooBeuts does this still happen in version 2.2 and above?

@TopStiGear what is the version of the mod you are using?

**Comment by TopStiGear** [comment]
@Rikmuld I would not know as I am using version for 1.7.10 for the modpack I am building

**Comment by Rikmuld** [comment]
Any issue with keys are most likely all fixed in the 1.8 version of the mod (2.2 and above). I basically won't update the 1.7.10 version anymore, but if I have some spare time I might release a fix for this for the 1.7.10 version.
