### ISSUE TITLE
What are the idem id's for iron stick/tent peg and a canvas

### ISSUE THREAD

**Issue by ryx123xs** [Rikmuld/CampingMod-mcmod#36]
I am trying to tweak the crafting so it's compatible with tfc, but I can't find the id's of the iron stick/tent peg or canvas anywhere, when I say id I mean name not number, i.e. camping:knife = Multitool/knife, camping:hempItem = a fully grow Hemp

**Comment by Rikmuld** [comment]
Have a look at this file: https://github.com/Rikmuld/CampingMod-mcmod/blob/master/Source/com/rikmuld/camping/core/Objects.scala

The id for metadata items will probably be the META_NAME(metadata), so for canvas it will just be camping:canvas.

**Comment by ryx123xs** [comment]
I have tried that and it did not work

**Comment by ryx123xs** [comment]
I have tried that and It didn't work, any other thoughts, I am using minetweaker three to do this if that information is of any help, Also I couldn't find the file for canvas or iron stick any where and was wondering if there was one or they are in a different file

**Comment by Rikmuld** [comment]
This file: https://github.com/Rikmuld/RikMuldsCore-mcmod/blob/405da37f6641167c9da86c4d46451745c2fad8dc/source/com/rikmuld/corerm/common/objs/item/ItemMain.scala is extended by all the items, simple items (for example the parts (canvas, iron stick etc.)) directly use that file.

I don't know how minetweaker works, but camping:canvas is most certainly the id of the canvas. Here you have a random guess about how it may handle items with damage values (so the canvas): 'MOD:ITEM_NAME:DAMAGE' for canvas that would be: 'camping:parts:0' (you can use the file Objects.scala to lookup the damage values and the names).

**Comment by ryx123xs** [comment]
OMG thank u it worked!!!!!!!
