### ISSUE TITLE
GUI Keybind Doesn't Re-Enable GUI

### ISSUE THREAD

**Issue by Surumon** [Rikmuld/CampingMod-mcmod#39]
Shutting off the GUI in it's configuration options disables the GUI entirely.

Binding a key in Options for the Camping Mod GUI (default is "C") does not function and re-enable the GUI or allow you to alter it's settings.

Still searching on workaround in the meantime, I have been unable to find one.

UPDATE: The only workaround I found was to delete the entire install and reinstall the entire MC directory.  I was unable to find where the actual config for this setting was stored.

Happy bug crunching.

**Comment by Rikmuld** [comment]
Fixed, an update will come out soon (it will be for Minecraft 1.8).

A workaround would be (for now, or if you don't want to update to Minecraft 1.8), either changing the key back to 'C', or manually editing the config options of the Camping Inventory in the config. You can in-game go to mods (in the main menu) and click on The Camping Mod, then click on config and search for: "Primary inventory option". Setting it to default will make the inventory appear again.
