### ISSUE TITLE
Crashes sometimes when using World Edit mod

### ISSUE THREAD

**Issue by jadenPete** [Rikmuld/CampingMod-mcmod#45]
Rarely when I'm using WorldEdit, it crashes. I know it's this mod because I see it in the log. Whenever this happens I'm not using anything in this mod, I'm just using the WorldEdit mod. Here's the link to my crash report:

http://pastebin.com/bPmUAfVL

**Comment by Rikmuld** [comment]
Added a safety to prevent this issue

**Comment by jadenPete** [comment]
Thanks. I'll download the latest version.

**Comment by Rikmuld** [comment]
Sorry, but I have yet to release the update with this fix included, I will release it later today.

**Comment by jadenPete** [comment]
Ok, Thanks!
