### ISSUE TITLE
java.lang.NullPointerException: Rendering screen

### ISSUE THREAD

**Issue by Dhs92** [Rikmuld/CampingMod-mcmod#47]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.115-universal.jar)
  MovingWorldCoreMod (movingworld-1.8-ALPHA-2.jar)
  FMLPlugin (InventoryTweaks-1.59-176.jar)
  CCCDeobfPlugin (unknown)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.34-universal.jar)
  ItemPatchingLoader (ItemPhysic Full 1.1.4 mc1.8.jar)
  DLFMLCorePlugin (DynamicLights-1.8.jar)
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.82-universal.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 7/8/15 8:32 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.minecraft.client.gui.GuiScreen.func_146270_b(GuiScreen.java:588)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:583)
	at com.rikmuld.camping.inventory.objs.GuiTent.func_73863_a(TentGui.scala:45)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:459)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1081)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.gui.GuiScreen.func_146270_b(GuiScreen.java:588)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:583)
	at com.rikmuld.camping.inventory.objs.GuiTent.func_73863_a(TentGui.scala:45)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:459)

-- Screen render details --
Details:
	Screen name: com.rikmuld.camping.inventory.objs.GuiTent
	Mouse location: Scaled: (554, 430). Absolute: (1280, 708)
	Screen size: Scaled: (1280, 709). Absolute: (2560, 1417). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Dhs92'/431, l='MpServer', x=-488.43, y=64.00, z=364.80]]
	Chunk stats: MultiplayerChunkCache: 259, 259
	Level seed: 0
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -88.00,64.00,256.00 - World: (-88,64,256), Chunk: (at 8,4,0 in -6,16; contains blocks -96,0,256 to -81,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 13066 game time, 13066 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 140 total; [EntityPig['Pig'/40993, l='MpServer', x=-446.50, y=75.00, z=300.28], EntityPig['Pig'/40994, l='MpServer', x=-441.50, y=74.00, z=299.16], EntityPig['Pig'/40995, l='MpServer', x=-440.50, y=73.00, z=303.50], EntityBird['Bird'/43047, l='MpServer', x=-502.50, y=65.00, z=379.06], EntityMouse['Mouse'/51250, l='MpServer', x=-425.47, y=23.00, z=345.75], EntityCentipede['Centipede'/57419, l='MpServer', x=-532.56, y=74.00, z=384.03], EntityBat['Bat'/61528, l='MpServer', x=-453.89, y=35.28, z=356.31], EntityMoth['Moth'/61531, l='MpServer', x=-410.95, y=12.58, z=430.44], EntityCentipede['Centipede'/55388, l='MpServer', x=-429.50, y=19.00, z=435.50], EntityMouse['Mouse'/61533, l='MpServer', x=-413.50, y=12.00, z=433.25], EntityCentipede['Centipede'/45183, l='MpServer', x=-471.50, y=70.00, z=301.50], EntityPig['Pig'/45249, l='MpServer', x=-536.50, y=71.00, z=437.44], EntityPig['Pig'/45250, l='MpServer', x=-536.50, y=71.00, z=438.91], EntityPig['Pig'/45251, l='MpServer', x=-538.50, y=71.00, z=438.50], EntityPig['Pig'/45252, l='MpServer', x=-536.50, y=71.00, z=440.19], EntityCow['Cow'/45254, l='MpServer', x=-537.19, y=65.00, z=311.50], EntityCow['Cow'/45255, l='MpServer', x=-538.50, y=64.00, z=308.50], EntityCow['Cow'/45256, l='MpServer', x=-540.50, y=72.00, z=307.50], EntityWitch['Witch'/59592, l='MpServer', x=-494.28, y=34.00, z=364.09], EntityCow['Cow'/45258, l='MpServer', x=-538.56, y=65.00, z=311.50], EntityZombie['Zombie'/61687, l='MpServer', x=-464.50, y=34.00, z=368.03], EntityPig['Pig'/45327, l='MpServer', x=-553.50, y=76.00, z=406.50], EntityPig['Pig'/45328, l='MpServer', x=-553.50, y=76.00, z=406.50], EntityPig['Pig'/45329, l='MpServer', x=-553.50, y=76.00, z=406.50], EntityPig['Pig'/45330, l='MpServer', x=-555.50, y=83.00, z=407.50], EntityMouse['Mouse'/61720, l='MpServer', x=-514.50, y=70.00, z=298.50], EntityMouse['Mouse'/53582, l='MpServer', x=-513.50, y=70.00, z=432.50], EntityCentipede['Centipede'/53589, l='MpServer', x=-474.13, y=38.00, z=362.53], Bear['Grizzly Bear'/41340, l='MpServer', x=-439.50, y=63.00, z=326.50], EntityMoth['Moth'/59800, l='MpServer', x=-424.25, y=21.00, z=435.75], EntityMouse['Mouse'/59824, l='MpServer', x=-469.50, y=15.00, z=436.50], EntityMouse['Mouse'/59843, l='MpServer', x=-519.50, y=66.00, z=397.19], EntityMouse['Mouse'/59872, l='MpServer', x=-435.44, y=40.00, z=435.22], EntityMoth['Moth'/59889, l='MpServer', x=-451.50, y=37.63, z=310.49], EntityMouse['Mouse'/59894, l='MpServer', x=-431.50, y=67.00, z=342.50], EntityCentipede['Centipede'/59897, l='MpServer', x=-479.50, y=70.00, z=295.50], EntityMouse['Mouse'/59904, l='MpServer', x=-437.50, y=40.00, z=429.50], EntityMouse['Mouse'/59905, l='MpServer', x=-438.50, y=40.00, z=429.50], EntityCentipede['Centipede'/59908, l='MpServer', x=-524.50, y=67.00, z=420.50], EntityCentipede['Centipede'/59910, l='MpServer', x=-527.50, y=67.00, z=418.50], EntityPlayerSP['Dhs92'/431, l='MpServer', x=-416.30, y=58.00, z=372.70], EntityCentipede['Centipede'/47639, l='MpServer', x=-546.03, y=71.00, z=293.63], EntityMouse['Mouse'/59928, l='MpServer', x=-442.34, y=72.00, z=304.72], EntityMouse['Mouse'/59935, l='MpServer', x=-526.59, y=70.00, z=376.47], EntityMouse['Mouse'/59936, l='MpServer', x=-508.59, y=66.91, z=379.23], EntityMouse['Mouse'/59937, l='MpServer', x=-508.72, y=67.00, z=363.69], EntityMouse['Mouse'/59938, l='MpServer', x=-525.50, y=71.00, z=361.75], EntityCentipede['Centipede'/59941, l='MpServer', x=-554.50, y=73.00, z=428.50], EntityMouse['Mouse'/59950, l='MpServer', x=-461.41, y=31.00, z=364.72], EntityZombie['Zombie'/64050, l='MpServer', x=-469.28, y=62.05, z=376.28], EntityWaterCreeper['entity.ElementalCreepers.elementalcreepers:WaterCreeper.name'/64051, l='MpServer', x=-456.50, y=63.00, z=378.50], EntityWindCreeper['entity.ElementalCreepers.elementalcreepers:WindCreeper.name'/64064, l='MpServer', x=-450.50, y=24.00, z=402.50], EntityMouse['Mouse'/59971, l='MpServer', x=-436.50, y=16.00, z=427.50], EntityMouse['Mouse'/59972, l='MpServer', x=-434.50, y=16.00, z=424.50], EntityMoth['Moth'/59973, l='MpServer', x=-422.25, y=14.00, z=422.25], EntityCentipede['Centipede'/59974, l='MpServer', x=-508.53, y=73.00, z=310.06], EntityMouse['Mouse'/59975, l='MpServer', x=-529.50, y=64.00, z=313.50], EntityPig['Pig'/45652, l='MpServer', x=-556.22, y=73.00, z=425.50], EntityCentipede['Centipede'/59988, l='MpServer', x=-517.69, y=77.00, z=285.94], EntityPig['Pig'/45653, l='MpServer', x=-557.56, y=73.00, z=425.50], EntityPig['Pig'/45654, l='MpServer', x=-557.09, y=73.00, z=421.06], EntityPig['Pig'/45655, l='MpServer', x=-554.50, y=72.00, z=425.50], EntityCentipede['Centipede'/59999, l='MpServer', x=-500.50, y=64.00, z=397.50], EntityCentipede['Centipede'/60007, l='MpServer', x=-466.03, y=61.00, z=353.16], EntityCentipede['Centipede'/60008, l='MpServer', x=-450.75, y=64.00, z=370.09], EntityCentipede['Centipede'/60009, l='MpServer', x=-459.50, y=64.00, z=362.50], EntityPig['Pig'/41578, l='MpServer', x=-461.06, y=62.34, z=415.75], EntityPig['Pig'/41579, l='MpServer', x=-460.97, y=63.00, z=412.91], EntityPig['Pig'/41580, l='MpServer', x=-463.59, y=63.00, z=413.34], EntityChicken['Chicken'/41586, l='MpServer', x=-451.72, y=72.00, z=309.28], EntityChicken['Chicken'/41587, l='MpServer', x=-453.31, y=72.00, z=309.38], EntityChicken['Chicken'/41588, l='MpServer', x=-450.69, y=72.00, z=309.91], EntityChicken['Chicken'/41589, l='MpServer', x=-453.50, y=71.00, z=311.50], Bear['Grizzly Bear'/41590, l='MpServer', x=-441.81, y=65.00, z=333.25], Camper['Camper'/41612, l='MpServer', x=-476.00, y=69.00, z=328.00], EntityPig['Pig'/41644, l='MpServer', x=-463.75, y=63.00, z=416.56], EntitySkeleton['Skeleton'/51911, l='MpServer', x=-445.09, y=24.00, z=316.44], EntityCreeper['Creeper'/60105, l='MpServer', x=-544.50, y=52.00, z=286.50], EntitySquid['Squid'/41686, l='MpServer', x=-469.27, y=61.16, z=377.44], EntityEarthCreeper['entity.ElementalCreepers.elementalcreepers:EarthCreeper.name'/60122, l='MpServer', x=-434.50, y=23.00, z=399.50], EntityZombie['Zombie'/60143, l='MpServer', x=-455.50, y=64.00, z=357.50], EntityCookieCreeper['entity.ElementalCreepers.elementalcreepers:CookieCreeper.name'/60149, l='MpServer', x=-485.50, y=42.00, z=323.50], EntityCookieCreeper['entity.ElementalCreepers.elementalcreepers:CookieCreeper.name'/60150, l='MpServer', x=-484.50, y=42.00, z=323.50], EntityCentipede['Centipede'/62209, l='MpServer', x=-465.66, y=27.00, z=410.50], EntityMouse['Mouse'/58129, l='MpServer', x=-523.50, y=71.00, z=315.50], EntityMouse['Mouse'/62225, l='MpServer', x=-558.50, y=71.00, z=300.50], EntityMouse['Mouse'/62226, l='MpServer', x=-559.50, y=71.00, z=300.50], EntityMouse['Mouse'/62227, l='MpServer', x=-560.50, y=71.00, z=295.50], EntityMouse['Mouse'/62228, l='MpServer', x=-562.50, y=71.00, z=290.50], EntityMouse['Mouse'/62240, l='MpServer', x=-558.50, y=72.00, z=368.25], EntityMouse['Mouse'/62243, l='MpServer', x=-557.53, y=62.47, z=365.41], EntityDragonfly['Dragonfly'/60237, l='MpServer', x=-409.47, y=64.00, z=306.25], EntityCentipede['Centipede'/60245, l='MpServer', x=-487.50, y=72.00, z=444.50], EntityCentipede['Centipede'/60264, l='MpServer', x=-422.50, y=28.00, z=349.50], EntityPlayerSP['Dhs92'/431, l='MpServer', x=-488.43, y=64.00, z=364.80], EntityItem['item.tile.sapling.oak'/64446, l='MpServer', x=-479.88, y=66.08, z=356.13], EntitySpider['Spider'/58348, l='MpServer', x=-502.31, y=21.09, z=387.28], EntityElectricCreeper['entity.ElementalCreepers.elementalcreepers:ElectricCreeper.name'/58350, l='MpServer', x=-493.50, y=19.00, z=393.50], EntityCentipede['Centipede'/48214, l='MpServer', x=-486.38, y=65.00, z=345.03], EntityMouse['Mouse'/60564, l='MpServer', x=-528.50, y=40.00, z=426.50], EntityMouse['Mouse'/60565, l='MpServer', x=-531.53, y=39.00, z=428.50], EntityCentipede['Centipede'/60579, l='MpServer', x=-548.50, y=72.00, z=433.50], EntityMouse['Mouse'/58645, l='MpServer', x=-550.56, y=66.00, z=333.19], EntityMouse['Mouse'/58646, l='MpServer', x=-547.63, y=66.02, z=329.75], EntityCentipede['Centipede'/58647, l='MpServer', x=-557.50, y=66.00, z=326.50], EntityDragonfly['Dragonfly'/58649, l='MpServer', x=-433.75, y=31.81, z=352.75], EntityMouse['Mouse'/54625, l='MpServer', x=-550.50, y=64.00, z=307.50], EntityCentipede['Centipede'/48522, l='MpServer', x=-519.28, y=71.00, z=384.13], EntityMouse['Mouse'/58790, l='MpServer', x=-556.50, y=71.00, z=384.50], EntityBat['Bat'/58948, l='MpServer', x=-468.28, y=47.06, z=408.03], EntityMouse['Mouse'/58949, l='MpServer', x=-476.50, y=47.02, z=413.50], EntityZombie['Zombie'/56930, l='MpServer', x=-490.50, y=45.00, z=398.50], EntityZombie['Zombie'/56932, l='MpServer', x=-489.50, y=45.00, z=399.50], EntityCreeper['Creeper'/59008, l='MpServer', x=-431.50, y=30.02, z=363.50], EntityItem['item.item.egg'/59034, l='MpServer', x=-452.69, y=72.00, z=309.56], EntitySkeleton['Skeleton'/54988, l='MpServer', x=-411.59, y=36.00, z=290.91], EntityPig['Pig'/48851, l='MpServer', x=-563.50, y=73.00, z=437.50], EntityPig['Pig'/48852, l='MpServer', x=-563.50, y=73.00, z=437.50], EntityPig['Pig'/48853, l='MpServer', x=-565.50, y=74.00, z=437.50], EntityPig['Pig'/48854, l='MpServer', x=-563.50, y=80.00, z=435.50], EntitySolarCreeper['entity.ElementalCreepers.elementalcreepers:SolarCreeper.name'/59099, l='MpServer', x=-436.50, y=48.00, z=338.50], EntityEnderman['Enderman'/63204, l='MpServer', x=-444.50, y=42.00, z=381.50], EntityEnderman['Enderman'/63205, l='MpServer', x=-446.31, y=43.00, z=380.50], EntityZombie['Zombie'/61177, l='MpServer', x=-415.34, y=13.00, z=436.81], EntitySkeleton['Skeleton'/61178, l='MpServer', x=-425.50, y=15.00, z=429.50], EntitySkeleton['Skeleton'/61179, l='MpServer', x=-423.50, y=15.00, z=432.50], EntitySkeleton['Skeleton'/61207, l='MpServer', x=-543.50, y=67.00, z=350.50], EntityMouse['Mouse'/53026, l='MpServer', x=-458.50, y=76.00, z=294.50], EntityCentipede['Centipede'/53048, l='MpServer', x=-530.50, y=64.00, z=309.50], EntityEarthCreeper['entity.ElementalCreepers.elementalcreepers:EarthCreeper.name'/55129, l='MpServer', x=-536.50, y=41.00, z=386.50], EntityEarthCreeper['entity.ElementalCreepers.elementalcreepers:EarthCreeper.name'/55130, l='MpServer', x=-538.50, y=41.00, z=384.50], EntityPig['Pig'/42901, l='MpServer', x=-494.47, y=64.00, z=416.44], EntityPig['Pig'/42902, l='MpServer', x=-487.53, y=64.00, z=426.69], EntityPig['Pig'/42903, l='MpServer', x=-493.97, y=64.00, z=419.41], EntityPig['Pig'/42904, l='MpServer', x=-492.81, y=64.00, z=419.50], EntityPig['Pig'/40879, l='MpServer', x=-443.03, y=72.00, z=306.25], EntityCreeper['Creeper'/59361, l='MpServer', x=-454.00, y=40.00, z=372.50], EntityCreeper['Creeper'/59362, l='MpServer', x=-453.25, y=39.00, z=371.41], EntityIceCreeper['entity.ElementalCreepers.elementalcreepers:IceCreeper.name'/59364, l='MpServer', x=-507.22, y=35.00, z=405.09], EntityEnderman['Enderman'/59366, l='MpServer', x=-446.50, y=24.00, z=431.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:351)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2502)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:367)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 877018856 bytes (836 MB) / 2027421696 bytes (1933 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 98
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1487 32 mods loaded, 32 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1487.jar) 
	UCHIJAAAA	Forge{11.14.3.1487} [Minecraft Forge] (forge-1.8-11.14.3.1487.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.5.34} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.82} [Not Enough Items] (NotEnoughItems-1.8-1.0.5.82-universal.jar) 
	UCHIJAAAA	darkevilmac.movingworld.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
	UCHIJAAAA	itemphysic{1.1.2} [ItemPhysic] (minecraft.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.3.3} [Damage Indicators] ([1.8]DamageIndicatorsMod-3.3.3.jar) 
	UCHIJAAAA	animalsplus{1.3} [Animals Plus] (animalsplus-1.3.jar) 
	UCHIJAAAA	MovingWorld{1.8-ALPHA-2} [Moving World] (movingworld-1.8-ALPHA-2.jar) 
	UCHIJAAAA	ArchimedesShipsPlus{1.8-ALPHA-2-HFX} [Archimedes' Ships Plus] (archimedesshipsplus-1.8-ALPHA-2-HFX.jar) 
	UCHIJAAAA	mymod{1.3.7} [Bash Cat's Weapon Arsenal] (BashArsenal1.8.jar) 
	UCHIJAAAA	DynamicLights{1.3.8} [Dynamic Lights] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	LomLib{4.1.0} [LomLib] (LomLib-1.8-4.1.0-universal.jar) 
	UCHIJAAAA	ElementalCreepers{5.0.0} [Elemental Creepers] (Elemental Creepers-universal-1.8-5.0.0.jar) 
	UCHIJAAAA	inventorytweaks{1.59-176-9318a76-dirty} [Inventory Tweaks] (InventoryTweaks-1.59-176.jar) 
	UCHIJAAAA	lucky{6.0.0} [Lucky Block] (LuckyBlock_1-8-3_v6-0-0.jar) 
	UCHIJAAAA	mineralogy{2.5.1} [Mineralogy] (mineralogy-2.5.1.jar) 
	UCHIJAAAA	minions{1.9.7} [Minions] (Minions-1.8.jar) 
	UCHIJAAAA	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7-build5(1.8).jar) 
	UCHIJAAAA	corerm{1.2} [RikMuld's Core] (RikMuldsCore_1.2.jar) 
	UCHIJAAAA	camping{2.2} [The Camping Mod 2] (TheCampingMod_2.2b.jar) 
	UCHIJAAAA	AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.8.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.115-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
MovingWorldCoreMod (movingworld-1.8-ALPHA-2.jar)
  
FMLPlugin (InventoryTweaks-1.59-176.jar)
  invtweaks.forge.asm.ContainerTransformer
CCCDeobfPlugin (unknown)
  
CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.34-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
ItemPatchingLoader (ItemPhysic Full 1.1.4 mc1.8.jar)
  com.creativemd.itemphysic.ItemTransformer
DLFMLCorePlugin (DynamicLights-1.8.jar)
  atomicstryker.dynamiclights.common.DLTransformer
NEICorePlugin (NotEnoughItems-1.8-1.0.5.82-universal.jar)
  codechicken.nei.asm.NEITransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.30' Renderer: 'GeForce GTX 660/PCIe/SSE2'
	Launched Version: 1.8
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 660/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.30, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [BDcraft Sounds Pack.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by Rikmuld** [comment]
Already fixed this (https://github.com/Rikmuld/CampingMod-mcmod/commit/8ef87d0e647c503f58fad5dcec77617bab6b9d70), I will release the update containing it later today.
