### ISSUE TITLE
Minecraft Crashes When I Click A Tent

### ISSUE THREAD

**Issue by jadenPete** [Rikmuld/CampingMod-mcmod#51]
When I Clicked my tent, the game crashed. My tent had two chests, a sleeping bag, and a fully fueled lantern. I have version 2.2d. Here's my crash report: http://pastebin.com/zjnY2HVe

**Comment by jadenPete** [comment]
Anyone?

**Comment by Rikmuld** [comment]
I will fix it today

**Comment by Rikmuld** [comment]
Fixed

**Comment by jadenPete** [comment]
Thank u
