### ISSUE TITLE
Bug when assign key

### ISSUE THREAD

**Issue by twgrm** [Rikmuld/CampingMod-mcmod#52]
Hey when I change the key from c to lets say 'b' it wont open the camping inventory, but if i change it back to 'c' the camping inventory work

**Comment by twgrm** [comment]
Forgot to mention Ilm using the 1.7.10 version

**Comment by Rikmuld** [comment]
Sadly, I no longer support the 1.7.10 version. This bug is only existent in Minecraft 1.7.10, if you upgrade to Minecraft 1.8 is is fixed.
