### ISSUE TITLE
Backpack duping bug on server. 2.1g

### ISSUE THREAD

**Issue by RandomColourzzz** [Rikmuld/CampingMod-mcmod#54]
I have the Camping Mod 2 installed on my server and when you die you keep the backpack and it drops also. Duping the contents of the backpack. I tested this on single player and it does not seem to happen. I am using cauldron 1.7 with some plugins. But mostly just Essentials, WorldGuard and WorldEdit. Thanks, fun mod and I hope I don't have to remove it. Also, is there a way disable the new menu GUI.

**Comment by Rikmuld** [comment]
Yes, this happens only when you use cauldron, a different type of server won't have this problem, I sadly can't seem to fix it. I don't know if it still happens in 1.8, at least I havent got any reports for it.
