### ISSUE TITLE
Cannot craft canvas 1.7.10 2.1g

### ISSUE THREAD

**Issue by Gunner76th** [Rikmuld/CampingMod-mcmod#58]
For some reason, I am unable to craft canvas from hemp. At first I thought the issue was with the knife, however even when I use creative to get a new undamaged knife, it is still uncraftable. I am able to use a knife with any damage value to craft the log seat as well as the sleeping bag, so it would seem that the issue is restricted to just turning hemp into canvas. 

MC 1.7.10
Forge 1492
Camping Mod 2.1g

**Comment by Rikmuld** [comment]
This bug is fixed the newer versions for MC 1.8. I'm sorry, but I won't work on the versions for MC 1.7.10 anymore.
