### ISSUE TITLE
Unable to create a "cooking fire" and use kits

### ISSUE THREAD

**Issue by Gunner76th** [Rikmuld/CampingMod-mcmod#59]
I have created a camp fire using the ring, flint, and 5 sticks. once I place it, if I right click on it a GUI appears. On the GUI, there is a box that appears to be an inventory of some sort, with a timer next to it. No mater what I try, the inventory slot does not accept any items, not coal, charcoal, logs, planks, or even kits. 

I am also unable to setup a kit over a campfire to use for cooking and such, which I assume is because I am unable to create a cooking campfire. 

MC 1.7.10
Forge 1492
Camping Mod 2.1g

**Comment by Rikmuld** [comment]
The cmpfire base is the cooking campfire, place that on the ground. This has been made more clear in the version for mc 1.8, sorry for the confusion.
