### ISSUE TITLE
PotionEffect(Bleeding) Conflict

### ISSUE THREAD

**Issue by Drakray** [Rikmuld/CampingMod-mcmod#69]
Artifacts mod equipment get Bleeding effect instead of whatever it's suppose to have.
Could maybe be fixed with configurable potion effect ID for Camping mod, but there is no such config.
Strangely, com.rikmuld.camping.misc.PotionBleeding is ID 0.
Using TheCampingMod_2.1g with Artifacts-1.1.3.
Posted problem on Artifacts's side too.
http://goo.gl/YmQWM2

**Comment by PitchBright** [comment]
@Drakray not sure if either one of these mods will help you or not, but may be worth a try:

http://www.curse.com/mc-mods/minecraft/229978-extended-potions
http://www.curse.com/mc-mods/minecraft/231384-potion-id-helper

**Comment by Drakray** [comment]
Potion ID Helper is in the modpack
NEI Potion ID CSV http://pastebin.com/GnuX7jU7
there is still place before 127, yet com.rikmuld.camping.misc.PotionBleeding is ID 0
Every potion I try give me Bleeding effet, I can't use NightVision

**Comment by PitchBright** [comment]
I was thinkin' maybe PotionIDHelper would let you reassign the IDs. Guess not. Yes/no?

**Comment by Drakray** [comment]
nop, that's just to get a file with conflict, and extend WAY past 127 the limit

**Comment by Drakray** [comment]
I might be stoopid.....
Look like I did thing wrong, and installed BOTH ExtendedPotion & PotionIDHelper...
removed ExtendedPotion, no more problem.
Can't say if conflict between them, or between Camping and ExtendedPotion, will check later
